config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :airplanes
  root 'welcome#index'

end

app/models/airplane.rb
class Airplane < ActiveRecord::Base
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
	
	def index
		@airplanes=Airplane.all
	end

	def new

	end

	def create
		@airplane = Airplane.new(airplane_params)
 		@airplane.save
  		redirect_to @airplane
	end

	def show
    	@airplane = Airplane.find(params[:id])
  	end

	private
  		def airplane_params
    		params.require(:airplane).permit(:name, :category, :passengers, :cabin_cubic_feet, :cargo_cubic_feet, :range, :speed)
  		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/airplanes/new.html.erb
<%= form_for :airplane, url: airplanes_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>

  <p>
    <%= f.label :passengers %><br>
    <%= f.text_field :passengers %>
  </p>
 
  <p>
    <%= f.label :cabin_cubic_feet %><br>
    <%= f.text_field :cabin_cubic_feet %>
  </p>

  <p>
    <%= f.label :cargo_cubic_feet %><br>
    <%= f.text_field :cargo_cubic_feet %>
  </p>

  <p>
    <%= f.label :range %><br>
    <%= f.text_field :range %>
  </p>

  <p>
    <%= f.label :speed %><br>
    <%= f.text_field :speed %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/airplanes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @airplane.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @airplane.category %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirplanesRangeWorking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>